baseURL = 'https://arc-en-ciel.io/'
languageCode = 'en-us'
title = '🌈 Arc-en-ciel.io'

theme         = "roxo-hugo"
summarylength = 25



[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 1
enableRobotsTXT = true


# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
#  [[menu.nav]]
#    name    = "Nous connaitre"
#    url     = "nous-connaitre"
#    weight  = 2
#  [[menu.nav]]
#    name    = "Articles"
#    url     = "blog"
#    weight  = 3
  [[menu.nav]]
    name    = "Mentions légales"
    url     = "mentionslegales"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  brand = "Arc-en-ciel"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Arc-en-ciel"
  author = "Grégory MARRO"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/Kv9zIdw"

  # Contact Form
  [params.contactForm]
    placeholder_last_name         = "Nom *"
    placeholder_first_name        = "Prénom *"
    placeholder_email             = "Email *"
    placeholder_company           = "Société *"
    placeholder_project_type      = "Type de project"
    placeholder_content           = "Comment pouvons-nous vous aider ?"
    placeholder_phone             = "Téléphone"
    send_message                  = "Envoyer"

    [[params.contactForm.projectType]]
      value = "audit"
      title  = "Audit"
    [[params.contactForm.projectType]]
      value = "conception"
      title  = "Conception/Intégration de solution"
    [[params.contactForm.projectType]]
      value = "migrationdccloud"
      title  = "Migration datacenter/cloud"
    [[params.contactForm.projectType]]
      value = "performances"
      title  = "Amélioration de performances"
    [[params.contactForm.projectType]]
      value = "conteneurisation"
      title  = "Conteneurisation d'applications"
    [[params.contactForm.projectType]]
      value = "cicd"
      title  = "Intégration continue"
    [[params.contactForm.projectType]]
      value = "developpement"
      title  = "Développement"
    [[params.contactForm.projectType]]
      value = "autre"
      title  = "Autre"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/circuitboard-background.webp"
    heading               = "L'architecture informatique à votre service"
    tagline               = "Exploitez tout le potentiel de votre système d'informations grâce à notre savoir-faire en architecture de solutions"
    primary_button        = "Nous contacter"
    primary_button_url    = "contact"
    secondary_button      = "Nos articles"
    secondary_button_url  = "blog"

  [params.portfolio]
    enable    = false
    title     = "Nos réalisations récentes"
    subtitle  = "Découvrez les projets "

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Avançons ensemble"
    primary_button      = "Nous contacter"
    primary_button_url  = "contact"
    secondary_button    = "Nos articles"
    secondary_button_url = "blog"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informations de contact"
      address = "1880 Route de Saint Jeannet,<br />Les Mas de Montalou, Villa 13<br /> 06700 Saint Laurent du Var"
      phone   = "06-20-72-34-63"
      email   = "contact@arc-en-ciel.io"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan de site"
#        [[params.footer.sitemap.link]]
#          name = "Articles"
#          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Mentions légales"
          url  = "mentionslegales"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux sociaux"
        enable = false
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "🌈 Arc-en-ciel"
        description = "L'architecture informatique à votre service"
