baseURL = 'https://arc-en-ciel.io/'
languageCode = 'en-us'
title = '🌈 Arc-en-ciel.io'

theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Nous connaitre"
    url     = "nous-connaitre"
    weight  = 2
  [[menu.nav]]
    name    = "Articles"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Mentions légales"
    url     = "mentionslegales"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Arc-en-ciel"
  author = "Grégory MARRO"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_last_name         = "Nom *"
    placeholder_first_name        = "Prénom *"
    placeholder_email             = "Email *"
    placeholder_company           = "Société *"
    placeholder_project_type      = "Type de project"
    placeholder_content           = "Comment pouvons-nous vous aider ?"
    placeholder_phone             = "Téléphone"
    send_message                  = "Envoyer"

    [[params.contactForm.projectType]]
      value = "audit"
      title  = "Audit"
    [[params.contactForm.projectType]]
      value = "conception"
      title  = "Conception/Intégration de solution"
    [[params.contactForm.projectType]]
      value = "conception"
      title  = "Conception/Intégration de solution"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/background-arc-en-ciel.png"
    heading               = "L'expertise open-source à votre service"
    tagline               = "Exploitez tout le potentiel de l'open-source pour votre entreprise grâce à notre savoir-faire en architecture de solutions"
    primary_button        = "En savoir plus"
    primary_button_url    = "a-propos"
    secondary_button      = "Nous contacter"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = false
    title     = "Nos réalisations récentes"
    subtitle  = "Découvrez les projets "

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Avançons ensemble"
    primary_button      = "Nous contacter"
    primary_button_url  = "contact"
    secondary_button    = "En savoir plus"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informations de contact"
      address = "🏢 1880 Route de Saint Jeannet,<br />Les Mas de Montalou, Villa 13<br /> 06700 Saint Laurent du Var"
      phone   = "📱 06-20-72-34-63"
      email   = "✉️ contact@arc-en-ciel.io"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Nous connaitre"
          url  = "nous-connaitre"
        [[params.footer.sitemap.link]]
          name = "Articles"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux sociaux"
        enable = false
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Notre solution"
        description = "L'expertise open-source pour votre entreprise"
